services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-rust-pypy-app
    container_name: rust_pypy_app
    ports:
      - "22:22"
    env_file:
      - .env
    volumes:
      - ./procon:/procon # ソースコードのマウント（開発中にコードを変更するため）
    environment:
      - PYTHONPATH=/procon # 必要に応じて環境変数を設定
    tty: true # 仮想端末を有効にする
