services:
  app:
    build:
      context: .
      args:
        - PORT=${PORT}
      dockerfile: Dockerfile
    image: my-rust-pypy-app
    container_name: rust_pypy_app
    ports:
      - "${PORT}:22"
    volumes:
      - ./procon:/procon # ソースコードのマウント（開発中にコードを変更するため）
    environment:
      - PYTHONPATH=/procon # 必要に応じて環境変数を設定
    tty: true # 仮想端末を有効にする
    restart: always